### ISSUE TITLE
Symbol not found: _libiconv_open

### ISSUE THREAD

**Issue by volkanunsal** [prontolabs/pronto#264]
This is the error I get when I run `pronto run`. What am I doing wrong?

```
dyld: lazy symbol binding failed: Symbol not found: _libiconv_open
  Referenced from: ~/gems/rugged-0.26.0/lib/rugged/rugged.bundle
  Expected in: flat namespace

dyld: Symbol not found: _libiconv_open
  Referenced from: ~/gems/rugged-0.26.0/lib/rugged/rugged.bundle
  Expected in: flat namespace

[1]    83093 trace trap  pronto run
```

**Comment by doomspork** [comment]
@volkanunsal have you tried Googling this at all?  I believe you're missing some of your command line dependencies, I don't think this relates to Pronto.

**Comment by volkanunsal** [comment]
@doomspork There is a lot of noise on Google search results. I haven't gotten anywhere following those threads.

**Comment by doomspork** [comment]
@volkanunsal can you run the rugged gem outside of Pronto without a problem?

**Comment by volkanunsal** [comment]
@doomspork Yes, I can. It only seems to happen when I run the binary.

```
➜  webapp (ruby-2.3.3) git:(tables) ✗ irb
[1] pry(main)> require 'rugged'
=> true
[2] pry(main)> require 'pronto'
=> true
[3] pry(main)>
➜  webapp (ruby-2.3.3) git:(tables) ✗ pronto run
dyld: lazy symbol binding failed: Symbol not found: _libiconv_open
  Referenced from: /Users/newuser/.rvm/gems/ruby-2.3.3@citiesense_search/gems/rugged-0.26.0/lib/rugged/rugged.bundle
  Expected in: flat namespace

dyld: Symbol not found: _libiconv_open
  Referenced from: /Users/newuser/.rvm/gems/ruby-2.3.3@citiesense_search/gems/rugged-0.26.0/lib/rugged/rugged.bundle
  Expected in: flat namespace

[1]    70471 trace trap  pronto run
```

**Comment by volkanunsal** [comment]
@doomspork 

I've narrowed the error to this codeblock.

```ruby
# lib/pronto.rb
 repo = Git::Repository.new(repo_path)
options = { paths: [file] } if file
patches = repo.diff(commit, options)
# ERROR!
```

**Comment by volkanunsal** [comment]
@doomspork 

The core issue is the libiconv framework. rugged is using the wrong headers of this framework.

      /Library/Frameworks/libiconv.framework/Headers/iconv.h

Here is how I fixed it

```
gem install rugged -- --with-opt-lib=/usr/local/opt/libiconv/lib --with-opt-include=/usr/local/opt/libiconv/include
```

**Comment by sfiddy** [comment]
Does anyone have another solution for this? I tried installing the way @volkanunsal suggested but I'm still getting the following error when i run pronto:

```
dyld: lazy symbol binding failed: Symbol not found: _libiconv_open
  Referenced from: /Users/steph/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rugged-0.27.7/lib/rugged/rugged.bundle
  Expected in: flat namespace

dyld: Symbol not found: _libiconv_open
  Referenced from: /Users/steph/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rugged-0.27.7/lib/rugged/rugged.bundle
  Expected in: flat namespace
```
